#!/usr/bin/env python3
"""Turn binary files into one C file of arrays, for what the runtime carries
inside itself: the homebrew loader a forwarder is built around, and the icons
its entry on the home menu shows."""
import sys, pathlib

def main(argv):
    out = pathlib.Path(argv[1])
    names = argv[2::2]
    paths = argv[3::2]
    lines = ["/* Generated by tools/make-embed.py. Do not edit. */",
             "#include <stddef.h>", ""]
    for name, path in zip(names, paths):
        data = pathlib.Path(path).read_bytes()
        lines.append("const unsigned char %s[] = {" % name)
        for i in range(0, len(data), 16):
            lines.append("    " + "".join("0x%02x," % b for b in data[i:i + 16]))
        lines.append("};")
        lines.append("const size_t %s_size = sizeof(%s);" % (name, name))
        lines.append("")
    out.write_text("\n".join(lines))
    return 0

if __name__ == "__main__":
    sys.exit(main(sys.argv))
